name: Go
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.22.0'
    - run: go build -o processor/native/testcmdbin github.com/pulchre/wingman/processor/native/testcmd
    - run: go test -cover -v -timeout 30s github.com/pulchre/wingman/...
